### PR TITLE
Get rid of broken flush feature in yaff.sampling.io

### PR DESCRIPTION
**Pull request by tovrstra**
@boegel See discussion in #23

### CODE REVIEW

**Comment by boegel** [comment]
@tovrstra lgtm, although this will affect other things that are using `flush=`?

Also: missing version bump?

**Comment by tovrstra** [comment]
So far, the flush feature was not used by the rest of YAFF but only in scripts that users wrote when using YAFF. (not common even).

I'll take care of the version bump, which reminds me that I also want to fix another small issue by the next release. Just a sec...

**Comment by tovrstra** [comment]
It is broken in the sense that it does not guarantee that the trajectory data is going to be readable when the script is killed. HDF5 files can get corrupted when not properly closed. Properly closing a HDF5 file is the only way to make sure that all data is written and will be readable later.

This also means that one cannot just let a job script on the HPC bump into the wall time limit. Instead, it should end in a proper way before that limit is reached.

**Comment by boegel** [comment]
@tovrstra In a job script, you could kill your program when you notice you're going to run out of walltime, using `kill <pid>`, which will send a `SIGTERM` signal.
If you catch that signal you can (flush &) close the HDF5 files properly to avoid corruption.

Making this airtight is less trivial though...

**Pull request merged**
