### PR TITLE
Fixed the computation of the vtens due to valence forces computed thr…

### PR DESCRIPTION
**Pull request by sandvdnh**
…ough a COMList

The back() method in the COMList should only be used to backpropagate gradients on centers of mass to gradients on atoms, NOT for the computation of the vtens due to forces on beads. (That vtens is computed by the dlist attribute of ForcePartValence).

### CODE REVIEW

**Comment by sandvdnh** [comment]
Hang on, something went wrong when adding the relevant test in test_comlist.py. This will get fixed in my next commit

**Comment by sandvdnh** [comment]
Fixed (hopefully).

**Comment by sandvdnh** [comment]
Apparently there's a whitespace issue in comlist.py, but I can't seem to find it.

**Comment by stevenvdb** [comment]
There is a script which automatically detects and fixes issues such as unwanted whitespace

wget https://raw.githubusercontent.com/tovrstra/devscripts/master/scripts/ds-normalize-code -O ds-normalize-code; chmod +x ds-normalize-code; ./ds-normalize-code;

**Comment by tovrstra** [comment]
Looks fine. Does the new test fail without the modified code?

**Comment by sandvdnh** [comment]
Yes, the new test failed without modifying comlist.back().

**Pull request merged**
